-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('ClietToServerProtocol_pb')


local LOGINREQ = protobuf.Descriptor();
local LOGINREQ_PLATFORM_FIELD = protobuf.FieldDescriptor();
local LOGINREQ_SERVER_FIELD = protobuf.FieldDescriptor();
local LOGINREQ_AUTHENCODE_FIELD = protobuf.FieldDescriptor();
local LOGINDATA = protobuf.Descriptor();
local LOGINDATA_USERNAME_FIELD = protobuf.FieldDescriptor();
local LOGINDATA_KEY_FIELD = protobuf.FieldDescriptor();
local LOGINDATA_GUID_FIELD = protobuf.FieldDescriptor();
local LOGINACK = protobuf.Descriptor();
local LOGINACK_ISSUCC_FIELD = protobuf.FieldDescriptor();
local LOGINACK_DATA_FIELD = protobuf.FieldDescriptor();
local LOGOUT = protobuf.Descriptor();
local LOGOUT_RESERVE_FIELD = protobuf.FieldDescriptor();

LOGINREQ_PLATFORM_FIELD.name = "platform"
LOGINREQ_PLATFORM_FIELD.full_name = ".LoginReq.platform"
LOGINREQ_PLATFORM_FIELD.number = 1
LOGINREQ_PLATFORM_FIELD.index = 0
LOGINREQ_PLATFORM_FIELD.label = 2
LOGINREQ_PLATFORM_FIELD.has_default_value = false
LOGINREQ_PLATFORM_FIELD.default_value = ""
LOGINREQ_PLATFORM_FIELD.type = 9
LOGINREQ_PLATFORM_FIELD.cpp_type = 9

LOGINREQ_SERVER_FIELD.name = "server"
LOGINREQ_SERVER_FIELD.full_name = ".LoginReq.server"
LOGINREQ_SERVER_FIELD.number = 2
LOGINREQ_SERVER_FIELD.index = 1
LOGINREQ_SERVER_FIELD.label = 2
LOGINREQ_SERVER_FIELD.has_default_value = false
LOGINREQ_SERVER_FIELD.default_value = ""
LOGINREQ_SERVER_FIELD.type = 9
LOGINREQ_SERVER_FIELD.cpp_type = 9

LOGINREQ_AUTHENCODE_FIELD.name = "authenCode"
LOGINREQ_AUTHENCODE_FIELD.full_name = ".LoginReq.authenCode"
LOGINREQ_AUTHENCODE_FIELD.number = 3
LOGINREQ_AUTHENCODE_FIELD.index = 2
LOGINREQ_AUTHENCODE_FIELD.label = 2
LOGINREQ_AUTHENCODE_FIELD.has_default_value = false
LOGINREQ_AUTHENCODE_FIELD.default_value = ""
LOGINREQ_AUTHENCODE_FIELD.type = 9
LOGINREQ_AUTHENCODE_FIELD.cpp_type = 9

LOGINREQ.name = "LoginReq"
LOGINREQ.full_name = ".LoginReq"
LOGINREQ.nested_types = {}
LOGINREQ.enum_types = {}
LOGINREQ.fields = {LOGINREQ_PLATFORM_FIELD, LOGINREQ_SERVER_FIELD, LOGINREQ_AUTHENCODE_FIELD}
LOGINREQ.is_extendable = false
LOGINREQ.extensions = {}
LOGINDATA_USERNAME_FIELD.name = "username"
LOGINDATA_USERNAME_FIELD.full_name = ".LoginData.username"
LOGINDATA_USERNAME_FIELD.number = 1
LOGINDATA_USERNAME_FIELD.index = 0
LOGINDATA_USERNAME_FIELD.label = 2
LOGINDATA_USERNAME_FIELD.has_default_value = false
LOGINDATA_USERNAME_FIELD.default_value = ""
LOGINDATA_USERNAME_FIELD.type = 9
LOGINDATA_USERNAME_FIELD.cpp_type = 9

LOGINDATA_KEY_FIELD.name = "key"
LOGINDATA_KEY_FIELD.full_name = ".LoginData.key"
LOGINDATA_KEY_FIELD.number = 2
LOGINDATA_KEY_FIELD.index = 1
LOGINDATA_KEY_FIELD.label = 2
LOGINDATA_KEY_FIELD.has_default_value = false
LOGINDATA_KEY_FIELD.default_value = ""
LOGINDATA_KEY_FIELD.type = 9
LOGINDATA_KEY_FIELD.cpp_type = 9

LOGINDATA_GUID_FIELD.name = "guid"
LOGINDATA_GUID_FIELD.full_name = ".LoginData.guid"
LOGINDATA_GUID_FIELD.number = 3
LOGINDATA_GUID_FIELD.index = 2
LOGINDATA_GUID_FIELD.label = 2
LOGINDATA_GUID_FIELD.has_default_value = false
LOGINDATA_GUID_FIELD.default_value = ""
LOGINDATA_GUID_FIELD.type = 9
LOGINDATA_GUID_FIELD.cpp_type = 9

LOGINDATA.name = "LoginData"
LOGINDATA.full_name = ".LoginData"
LOGINDATA.nested_types = {}
LOGINDATA.enum_types = {}
LOGINDATA.fields = {LOGINDATA_USERNAME_FIELD, LOGINDATA_KEY_FIELD, LOGINDATA_GUID_FIELD}
LOGINDATA.is_extendable = false
LOGINDATA.extensions = {}
LOGINACK_ISSUCC_FIELD.name = "isSucc"
LOGINACK_ISSUCC_FIELD.full_name = ".LoginAck.isSucc"
LOGINACK_ISSUCC_FIELD.number = 1
LOGINACK_ISSUCC_FIELD.index = 0
LOGINACK_ISSUCC_FIELD.label = 2
LOGINACK_ISSUCC_FIELD.has_default_value = false
LOGINACK_ISSUCC_FIELD.default_value = false
LOGINACK_ISSUCC_FIELD.type = 8
LOGINACK_ISSUCC_FIELD.cpp_type = 7

LOGINACK_DATA_FIELD.name = "data"
LOGINACK_DATA_FIELD.full_name = ".LoginAck.data"
LOGINACK_DATA_FIELD.number = 2
LOGINACK_DATA_FIELD.index = 1
LOGINACK_DATA_FIELD.label = 1
LOGINACK_DATA_FIELD.has_default_value = false
LOGINACK_DATA_FIELD.default_value = nil
LOGINACK_DATA_FIELD.message_type = LOGINDATA
LOGINACK_DATA_FIELD.type = 11
LOGINACK_DATA_FIELD.cpp_type = 10

LOGINACK.name = "LoginAck"
LOGINACK.full_name = ".LoginAck"
LOGINACK.nested_types = {}
LOGINACK.enum_types = {}
LOGINACK.fields = {LOGINACK_ISSUCC_FIELD, LOGINACK_DATA_FIELD}
LOGINACK.is_extendable = false
LOGINACK.extensions = {}
LOGOUT_RESERVE_FIELD.name = "reserve"
LOGOUT_RESERVE_FIELD.full_name = ".Logout.reserve"
LOGOUT_RESERVE_FIELD.number = 1
LOGOUT_RESERVE_FIELD.index = 0
LOGOUT_RESERVE_FIELD.label = 2
LOGOUT_RESERVE_FIELD.has_default_value = false
LOGOUT_RESERVE_FIELD.default_value = 0
LOGOUT_RESERVE_FIELD.type = 5
LOGOUT_RESERVE_FIELD.cpp_type = 1

LOGOUT.name = "Logout"
LOGOUT.full_name = ".Logout"
LOGOUT.nested_types = {}
LOGOUT.enum_types = {}
LOGOUT.fields = {LOGOUT_RESERVE_FIELD}
LOGOUT.is_extendable = false
LOGOUT.extensions = {}

LoginAck = protobuf.Message(LOGINACK)
LoginData = protobuf.Message(LOGINDATA)
LoginReq = protobuf.Message(LOGINREQ)
Logout = protobuf.Message(LOGOUT)

