-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('GateToTSProtocol_pb')


local REPORTGATE = protobuf.Descriptor();
local REPORTGATE_ID_FIELD = protobuf.FieldDescriptor();
local CREATEPLAYER = protobuf.Descriptor();
local CREATEPLAYER_ID_FIELD = protobuf.FieldDescriptor();
local DESTORYPLAYER = protobuf.Descriptor();
local DESTORYPLAYER_ID_FIELD = protobuf.FieldDescriptor();
local PLAYERMESSAGE = protobuf.Descriptor();
local PLAYERMESSAGE_ID_FIELD = protobuf.FieldDescriptor();
local PLAYERMESSAGE_DATA_FIELD = protobuf.FieldDescriptor();
local KICKOFF = protobuf.Descriptor();
local KICKOFF_ID_FIELD = protobuf.FieldDescriptor();

REPORTGATE_ID_FIELD.name = "id"
REPORTGATE_ID_FIELD.full_name = ".ReportGate.id"
REPORTGATE_ID_FIELD.number = 1
REPORTGATE_ID_FIELD.index = 0
REPORTGATE_ID_FIELD.label = 2
REPORTGATE_ID_FIELD.has_default_value = false
REPORTGATE_ID_FIELD.default_value = 0
REPORTGATE_ID_FIELD.type = 5
REPORTGATE_ID_FIELD.cpp_type = 1

REPORTGATE.name = "ReportGate"
REPORTGATE.full_name = ".ReportGate"
REPORTGATE.nested_types = {}
REPORTGATE.enum_types = {}
REPORTGATE.fields = {REPORTGATE_ID_FIELD}
REPORTGATE.is_extendable = false
REPORTGATE.extensions = {}
CREATEPLAYER_ID_FIELD.name = "id"
CREATEPLAYER_ID_FIELD.full_name = ".CreatePlayer.id"
CREATEPLAYER_ID_FIELD.number = 1
CREATEPLAYER_ID_FIELD.index = 0
CREATEPLAYER_ID_FIELD.label = 2
CREATEPLAYER_ID_FIELD.has_default_value = false
CREATEPLAYER_ID_FIELD.default_value = 0
CREATEPLAYER_ID_FIELD.type = 5
CREATEPLAYER_ID_FIELD.cpp_type = 1

CREATEPLAYER.name = "CreatePlayer"
CREATEPLAYER.full_name = ".CreatePlayer"
CREATEPLAYER.nested_types = {}
CREATEPLAYER.enum_types = {}
CREATEPLAYER.fields = {CREATEPLAYER_ID_FIELD}
CREATEPLAYER.is_extendable = false
CREATEPLAYER.extensions = {}
DESTORYPLAYER_ID_FIELD.name = "id"
DESTORYPLAYER_ID_FIELD.full_name = ".DestoryPlayer.id"
DESTORYPLAYER_ID_FIELD.number = 1
DESTORYPLAYER_ID_FIELD.index = 0
DESTORYPLAYER_ID_FIELD.label = 2
DESTORYPLAYER_ID_FIELD.has_default_value = false
DESTORYPLAYER_ID_FIELD.default_value = 0
DESTORYPLAYER_ID_FIELD.type = 5
DESTORYPLAYER_ID_FIELD.cpp_type = 1

DESTORYPLAYER.name = "DestoryPlayer"
DESTORYPLAYER.full_name = ".DestoryPlayer"
DESTORYPLAYER.nested_types = {}
DESTORYPLAYER.enum_types = {}
DESTORYPLAYER.fields = {DESTORYPLAYER_ID_FIELD}
DESTORYPLAYER.is_extendable = false
DESTORYPLAYER.extensions = {}
PLAYERMESSAGE_ID_FIELD.name = "id"
PLAYERMESSAGE_ID_FIELD.full_name = ".PlayerMessage.id"
PLAYERMESSAGE_ID_FIELD.number = 1
PLAYERMESSAGE_ID_FIELD.index = 0
PLAYERMESSAGE_ID_FIELD.label = 2
PLAYERMESSAGE_ID_FIELD.has_default_value = false
PLAYERMESSAGE_ID_FIELD.default_value = 0
PLAYERMESSAGE_ID_FIELD.type = 5
PLAYERMESSAGE_ID_FIELD.cpp_type = 1

PLAYERMESSAGE_DATA_FIELD.name = "data"
PLAYERMESSAGE_DATA_FIELD.full_name = ".PlayerMessage.data"
PLAYERMESSAGE_DATA_FIELD.number = 2
PLAYERMESSAGE_DATA_FIELD.index = 1
PLAYERMESSAGE_DATA_FIELD.label = 2
PLAYERMESSAGE_DATA_FIELD.has_default_value = false
PLAYERMESSAGE_DATA_FIELD.default_value = ""
PLAYERMESSAGE_DATA_FIELD.type = 9
PLAYERMESSAGE_DATA_FIELD.cpp_type = 9

PLAYERMESSAGE.name = "PlayerMessage"
PLAYERMESSAGE.full_name = ".PlayerMessage"
PLAYERMESSAGE.nested_types = {}
PLAYERMESSAGE.enum_types = {}
PLAYERMESSAGE.fields = {PLAYERMESSAGE_ID_FIELD, PLAYERMESSAGE_DATA_FIELD}
PLAYERMESSAGE.is_extendable = false
PLAYERMESSAGE.extensions = {}
KICKOFF_ID_FIELD.name = "id"
KICKOFF_ID_FIELD.full_name = ".KickOff.id"
KICKOFF_ID_FIELD.number = 1
KICKOFF_ID_FIELD.index = 0
KICKOFF_ID_FIELD.label = 2
KICKOFF_ID_FIELD.has_default_value = false
KICKOFF_ID_FIELD.default_value = 0
KICKOFF_ID_FIELD.type = 5
KICKOFF_ID_FIELD.cpp_type = 1

KICKOFF.name = "KickOff"
KICKOFF.full_name = ".KickOff"
KICKOFF.nested_types = {}
KICKOFF.enum_types = {}
KICKOFF.fields = {KICKOFF_ID_FIELD}
KICKOFF.is_extendable = false
KICKOFF.extensions = {}

CreatePlayer = protobuf.Message(CREATEPLAYER)
DestoryPlayer = protobuf.Message(DESTORYPLAYER)
KickOff = protobuf.Message(KICKOFF)
PlayerMessage = protobuf.Message(PLAYERMESSAGE)
ReportGate = protobuf.Message(REPORTGATE)

