-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('NodeProtocol_pb')


local REPORT = protobuf.Descriptor();
local REPORT_NODETYPE_FIELD = protobuf.FieldDescriptor();
local REPORT_NODEID_FIELD = protobuf.FieldDescriptor();
local REPORT_URI_FIELD = protobuf.FieldDescriptor();
local MESSAGE = protobuf.Descriptor();
local MESSAGE_MSG_FIELD = protobuf.FieldDescriptor();

REPORT_NODETYPE_FIELD.name = "nodeType"
REPORT_NODETYPE_FIELD.full_name = ".Report.nodeType"
REPORT_NODETYPE_FIELD.number = 1
REPORT_NODETYPE_FIELD.index = 0
REPORT_NODETYPE_FIELD.label = 2
REPORT_NODETYPE_FIELD.has_default_value = false
REPORT_NODETYPE_FIELD.default_value = ""
REPORT_NODETYPE_FIELD.type = 9
REPORT_NODETYPE_FIELD.cpp_type = 9

REPORT_NODEID_FIELD.name = "nodeId"
REPORT_NODEID_FIELD.full_name = ".Report.nodeId"
REPORT_NODEID_FIELD.number = 2
REPORT_NODEID_FIELD.index = 1
REPORT_NODEID_FIELD.label = 2
REPORT_NODEID_FIELD.has_default_value = false
REPORT_NODEID_FIELD.default_value = ""
REPORT_NODEID_FIELD.type = 9
REPORT_NODEID_FIELD.cpp_type = 9

REPORT_URI_FIELD.name = "uri"
REPORT_URI_FIELD.full_name = ".Report.uri"
REPORT_URI_FIELD.number = 3
REPORT_URI_FIELD.index = 2
REPORT_URI_FIELD.label = 2
REPORT_URI_FIELD.has_default_value = false
REPORT_URI_FIELD.default_value = ""
REPORT_URI_FIELD.type = 9
REPORT_URI_FIELD.cpp_type = 9

REPORT.name = "Report"
REPORT.full_name = ".Report"
REPORT.nested_types = {}
REPORT.enum_types = {}
REPORT.fields = {REPORT_NODETYPE_FIELD, REPORT_NODEID_FIELD, REPORT_URI_FIELD}
REPORT.is_extendable = false
REPORT.extensions = {}
MESSAGE_MSG_FIELD.name = "msg"
MESSAGE_MSG_FIELD.full_name = ".Message.msg"
MESSAGE_MSG_FIELD.number = 1
MESSAGE_MSG_FIELD.index = 0
MESSAGE_MSG_FIELD.label = 2
MESSAGE_MSG_FIELD.has_default_value = false
MESSAGE_MSG_FIELD.default_value = ""
MESSAGE_MSG_FIELD.type = 9
MESSAGE_MSG_FIELD.cpp_type = 9

MESSAGE.name = "Message"
MESSAGE.full_name = ".Message"
MESSAGE.nested_types = {}
MESSAGE.enum_types = {}
MESSAGE.fields = {MESSAGE_MSG_FIELD}
MESSAGE.is_extendable = false
MESSAGE.extensions = {}

Message = protobuf.Message(MESSAGE)
Report = protobuf.Message(REPORT)

