-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('TSToLSProtocol_pb')


local AUTHENREQ = protobuf.Descriptor();
local AUTHENREQ_GATEID_FIELD = protobuf.FieldDescriptor();
local AUTHENREQ_INGATEID_FIELD = protobuf.FieldDescriptor();
local AUTHENREQ_PLATFORM_FIELD = protobuf.FieldDescriptor();
local AUTHENREQ_AUTHENCODE_FIELD = protobuf.FieldDescriptor();
local AUTHENDATA = protobuf.Descriptor();
local AUTHENDATA_ISSUCC_FIELD = protobuf.FieldDescriptor();
local AUTHENDATA_USERNAME_FIELD = protobuf.FieldDescriptor();
local AUTHENACK = protobuf.Descriptor();
local AUTHENACK_GATEID_FIELD = protobuf.FieldDescriptor();
local AUTHENACK_INGATEID_FIELD = protobuf.FieldDescriptor();
local AUTHENACK_DATA_FIELD = protobuf.FieldDescriptor();

AUTHENREQ_GATEID_FIELD.name = "gateId"
AUTHENREQ_GATEID_FIELD.full_name = ".AuthenReq.gateId"
AUTHENREQ_GATEID_FIELD.number = 1
AUTHENREQ_GATEID_FIELD.index = 0
AUTHENREQ_GATEID_FIELD.label = 2
AUTHENREQ_GATEID_FIELD.has_default_value = false
AUTHENREQ_GATEID_FIELD.default_value = 0
AUTHENREQ_GATEID_FIELD.type = 5
AUTHENREQ_GATEID_FIELD.cpp_type = 1

AUTHENREQ_INGATEID_FIELD.name = "inGateId"
AUTHENREQ_INGATEID_FIELD.full_name = ".AuthenReq.inGateId"
AUTHENREQ_INGATEID_FIELD.number = 2
AUTHENREQ_INGATEID_FIELD.index = 1
AUTHENREQ_INGATEID_FIELD.label = 2
AUTHENREQ_INGATEID_FIELD.has_default_value = false
AUTHENREQ_INGATEID_FIELD.default_value = 0
AUTHENREQ_INGATEID_FIELD.type = 5
AUTHENREQ_INGATEID_FIELD.cpp_type = 1

AUTHENREQ_PLATFORM_FIELD.name = "platform"
AUTHENREQ_PLATFORM_FIELD.full_name = ".AuthenReq.platform"
AUTHENREQ_PLATFORM_FIELD.number = 3
AUTHENREQ_PLATFORM_FIELD.index = 2
AUTHENREQ_PLATFORM_FIELD.label = 2
AUTHENREQ_PLATFORM_FIELD.has_default_value = false
AUTHENREQ_PLATFORM_FIELD.default_value = ""
AUTHENREQ_PLATFORM_FIELD.type = 9
AUTHENREQ_PLATFORM_FIELD.cpp_type = 9

AUTHENREQ_AUTHENCODE_FIELD.name = "authenCode"
AUTHENREQ_AUTHENCODE_FIELD.full_name = ".AuthenReq.authenCode"
AUTHENREQ_AUTHENCODE_FIELD.number = 4
AUTHENREQ_AUTHENCODE_FIELD.index = 3
AUTHENREQ_AUTHENCODE_FIELD.label = 2
AUTHENREQ_AUTHENCODE_FIELD.has_default_value = false
AUTHENREQ_AUTHENCODE_FIELD.default_value = ""
AUTHENREQ_AUTHENCODE_FIELD.type = 9
AUTHENREQ_AUTHENCODE_FIELD.cpp_type = 9

AUTHENREQ.name = "AuthenReq"
AUTHENREQ.full_name = ".AuthenReq"
AUTHENREQ.nested_types = {}
AUTHENREQ.enum_types = {}
AUTHENREQ.fields = {AUTHENREQ_GATEID_FIELD, AUTHENREQ_INGATEID_FIELD, AUTHENREQ_PLATFORM_FIELD, AUTHENREQ_AUTHENCODE_FIELD}
AUTHENREQ.is_extendable = false
AUTHENREQ.extensions = {}
AUTHENDATA_ISSUCC_FIELD.name = "isSucc"
AUTHENDATA_ISSUCC_FIELD.full_name = ".AuthenData.isSucc"
AUTHENDATA_ISSUCC_FIELD.number = 1
AUTHENDATA_ISSUCC_FIELD.index = 0
AUTHENDATA_ISSUCC_FIELD.label = 2
AUTHENDATA_ISSUCC_FIELD.has_default_value = false
AUTHENDATA_ISSUCC_FIELD.default_value = false
AUTHENDATA_ISSUCC_FIELD.type = 8
AUTHENDATA_ISSUCC_FIELD.cpp_type = 7

AUTHENDATA_USERNAME_FIELD.name = "username"
AUTHENDATA_USERNAME_FIELD.full_name = ".AuthenData.username"
AUTHENDATA_USERNAME_FIELD.number = 2
AUTHENDATA_USERNAME_FIELD.index = 1
AUTHENDATA_USERNAME_FIELD.label = 1
AUTHENDATA_USERNAME_FIELD.has_default_value = false
AUTHENDATA_USERNAME_FIELD.default_value = ""
AUTHENDATA_USERNAME_FIELD.type = 9
AUTHENDATA_USERNAME_FIELD.cpp_type = 9

AUTHENDATA.name = "AuthenData"
AUTHENDATA.full_name = ".AuthenData"
AUTHENDATA.nested_types = {}
AUTHENDATA.enum_types = {}
AUTHENDATA.fields = {AUTHENDATA_ISSUCC_FIELD, AUTHENDATA_USERNAME_FIELD}
AUTHENDATA.is_extendable = false
AUTHENDATA.extensions = {}
AUTHENACK_GATEID_FIELD.name = "gateId"
AUTHENACK_GATEID_FIELD.full_name = ".AuthenAck.gateId"
AUTHENACK_GATEID_FIELD.number = 1
AUTHENACK_GATEID_FIELD.index = 0
AUTHENACK_GATEID_FIELD.label = 2
AUTHENACK_GATEID_FIELD.has_default_value = false
AUTHENACK_GATEID_FIELD.default_value = 0
AUTHENACK_GATEID_FIELD.type = 5
AUTHENACK_GATEID_FIELD.cpp_type = 1

AUTHENACK_INGATEID_FIELD.name = "inGateId"
AUTHENACK_INGATEID_FIELD.full_name = ".AuthenAck.inGateId"
AUTHENACK_INGATEID_FIELD.number = 2
AUTHENACK_INGATEID_FIELD.index = 1
AUTHENACK_INGATEID_FIELD.label = 2
AUTHENACK_INGATEID_FIELD.has_default_value = false
AUTHENACK_INGATEID_FIELD.default_value = 0
AUTHENACK_INGATEID_FIELD.type = 5
AUTHENACK_INGATEID_FIELD.cpp_type = 1

AUTHENACK_DATA_FIELD.name = "data"
AUTHENACK_DATA_FIELD.full_name = ".AuthenAck.data"
AUTHENACK_DATA_FIELD.number = 3
AUTHENACK_DATA_FIELD.index = 2
AUTHENACK_DATA_FIELD.label = 2
AUTHENACK_DATA_FIELD.has_default_value = false
AUTHENACK_DATA_FIELD.default_value = nil
AUTHENACK_DATA_FIELD.message_type = AUTHENDATA
AUTHENACK_DATA_FIELD.type = 11
AUTHENACK_DATA_FIELD.cpp_type = 10

AUTHENACK.name = "AuthenAck"
AUTHENACK.full_name = ".AuthenAck"
AUTHENACK.nested_types = {}
AUTHENACK.enum_types = {}
AUTHENACK.fields = {AUTHENACK_GATEID_FIELD, AUTHENACK_INGATEID_FIELD, AUTHENACK_DATA_FIELD}
AUTHENACK.is_extendable = false
AUTHENACK.extensions = {}

AuthenAck = protobuf.Message(AUTHENACK)
AuthenData = protobuf.Message(AUTHENDATA)
AuthenReq = protobuf.Message(AUTHENREQ)

