-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('TSToCSProtocol_pb')


local LOADREQ = protobuf.Descriptor();
local LOADREQ_GATEID_FIELD = protobuf.FieldDescriptor();
local LOADREQ_INGATEID_FIELD = protobuf.FieldDescriptor();
local LOADREQ_PLATFORM_FIELD = protobuf.FieldDescriptor();
local LOADREQ_SERVER_FIELD = protobuf.FieldDescriptor();
local LOADREQ_USERNAME_FIELD = protobuf.FieldDescriptor();
local LOADDATA = protobuf.Descriptor();
local LOADDATA_ISSUCC_FIELD = protobuf.FieldDescriptor();
local LOADDATA_GUID_FIELD = protobuf.FieldDescriptor();
local LOADACK = protobuf.Descriptor();
local LOADACK_GATEID_FIELD = protobuf.FieldDescriptor();
local LOADACK_INGATEID_FIELD = protobuf.FieldDescriptor();
local LOADACK_DATA_FIELD = protobuf.FieldDescriptor();
local CHECKANDNOTIFYOFFLINE = protobuf.Descriptor();
local CHECKANDNOTIFYOFFLINE_GATEID_FIELD = protobuf.FieldDescriptor();
local CHECKANDNOTIFYOFFLINE_INGATEID_FIELD = protobuf.FieldDescriptor();
local CHECKANDNOTIFYOFFLINE_GUID_FIELD = protobuf.FieldDescriptor();
local KICKOFF = protobuf.Descriptor();
local KICKOFF_GUID_FIELD = protobuf.FieldDescriptor();

LOADREQ_GATEID_FIELD.name = "gateId"
LOADREQ_GATEID_FIELD.full_name = ".LoadReq.gateId"
LOADREQ_GATEID_FIELD.number = 1
LOADREQ_GATEID_FIELD.index = 0
LOADREQ_GATEID_FIELD.label = 2
LOADREQ_GATEID_FIELD.has_default_value = false
LOADREQ_GATEID_FIELD.default_value = 0
LOADREQ_GATEID_FIELD.type = 5
LOADREQ_GATEID_FIELD.cpp_type = 1

LOADREQ_INGATEID_FIELD.name = "inGateId"
LOADREQ_INGATEID_FIELD.full_name = ".LoadReq.inGateId"
LOADREQ_INGATEID_FIELD.number = 2
LOADREQ_INGATEID_FIELD.index = 1
LOADREQ_INGATEID_FIELD.label = 2
LOADREQ_INGATEID_FIELD.has_default_value = false
LOADREQ_INGATEID_FIELD.default_value = 0
LOADREQ_INGATEID_FIELD.type = 5
LOADREQ_INGATEID_FIELD.cpp_type = 1

LOADREQ_PLATFORM_FIELD.name = "platform"
LOADREQ_PLATFORM_FIELD.full_name = ".LoadReq.platform"
LOADREQ_PLATFORM_FIELD.number = 3
LOADREQ_PLATFORM_FIELD.index = 2
LOADREQ_PLATFORM_FIELD.label = 2
LOADREQ_PLATFORM_FIELD.has_default_value = false
LOADREQ_PLATFORM_FIELD.default_value = ""
LOADREQ_PLATFORM_FIELD.type = 9
LOADREQ_PLATFORM_FIELD.cpp_type = 9

LOADREQ_SERVER_FIELD.name = "server"
LOADREQ_SERVER_FIELD.full_name = ".LoadReq.server"
LOADREQ_SERVER_FIELD.number = 4
LOADREQ_SERVER_FIELD.index = 3
LOADREQ_SERVER_FIELD.label = 2
LOADREQ_SERVER_FIELD.has_default_value = false
LOADREQ_SERVER_FIELD.default_value = ""
LOADREQ_SERVER_FIELD.type = 9
LOADREQ_SERVER_FIELD.cpp_type = 9

LOADREQ_USERNAME_FIELD.name = "username"
LOADREQ_USERNAME_FIELD.full_name = ".LoadReq.username"
LOADREQ_USERNAME_FIELD.number = 5
LOADREQ_USERNAME_FIELD.index = 4
LOADREQ_USERNAME_FIELD.label = 2
LOADREQ_USERNAME_FIELD.has_default_value = false
LOADREQ_USERNAME_FIELD.default_value = ""
LOADREQ_USERNAME_FIELD.type = 9
LOADREQ_USERNAME_FIELD.cpp_type = 9

LOADREQ.name = "LoadReq"
LOADREQ.full_name = ".LoadReq"
LOADREQ.nested_types = {}
LOADREQ.enum_types = {}
LOADREQ.fields = {LOADREQ_GATEID_FIELD, LOADREQ_INGATEID_FIELD, LOADREQ_PLATFORM_FIELD, LOADREQ_SERVER_FIELD, LOADREQ_USERNAME_FIELD}
LOADREQ.is_extendable = false
LOADREQ.extensions = {}
LOADDATA_ISSUCC_FIELD.name = "isSucc"
LOADDATA_ISSUCC_FIELD.full_name = ".LoadData.isSucc"
LOADDATA_ISSUCC_FIELD.number = 1
LOADDATA_ISSUCC_FIELD.index = 0
LOADDATA_ISSUCC_FIELD.label = 2
LOADDATA_ISSUCC_FIELD.has_default_value = false
LOADDATA_ISSUCC_FIELD.default_value = false
LOADDATA_ISSUCC_FIELD.type = 8
LOADDATA_ISSUCC_FIELD.cpp_type = 7

LOADDATA_GUID_FIELD.name = "guid"
LOADDATA_GUID_FIELD.full_name = ".LoadData.guid"
LOADDATA_GUID_FIELD.number = 2
LOADDATA_GUID_FIELD.index = 1
LOADDATA_GUID_FIELD.label = 1
LOADDATA_GUID_FIELD.has_default_value = false
LOADDATA_GUID_FIELD.default_value = ""
LOADDATA_GUID_FIELD.type = 9
LOADDATA_GUID_FIELD.cpp_type = 9

LOADDATA.name = "LoadData"
LOADDATA.full_name = ".LoadData"
LOADDATA.nested_types = {}
LOADDATA.enum_types = {}
LOADDATA.fields = {LOADDATA_ISSUCC_FIELD, LOADDATA_GUID_FIELD}
LOADDATA.is_extendable = false
LOADDATA.extensions = {}
LOADACK_GATEID_FIELD.name = "gateId"
LOADACK_GATEID_FIELD.full_name = ".LoadAck.gateId"
LOADACK_GATEID_FIELD.number = 1
LOADACK_GATEID_FIELD.index = 0
LOADACK_GATEID_FIELD.label = 2
LOADACK_GATEID_FIELD.has_default_value = false
LOADACK_GATEID_FIELD.default_value = 0
LOADACK_GATEID_FIELD.type = 5
LOADACK_GATEID_FIELD.cpp_type = 1

LOADACK_INGATEID_FIELD.name = "inGateId"
LOADACK_INGATEID_FIELD.full_name = ".LoadAck.inGateId"
LOADACK_INGATEID_FIELD.number = 2
LOADACK_INGATEID_FIELD.index = 1
LOADACK_INGATEID_FIELD.label = 2
LOADACK_INGATEID_FIELD.has_default_value = false
LOADACK_INGATEID_FIELD.default_value = 0
LOADACK_INGATEID_FIELD.type = 5
LOADACK_INGATEID_FIELD.cpp_type = 1

LOADACK_DATA_FIELD.name = "data"
LOADACK_DATA_FIELD.full_name = ".LoadAck.data"
LOADACK_DATA_FIELD.number = 3
LOADACK_DATA_FIELD.index = 2
LOADACK_DATA_FIELD.label = 2
LOADACK_DATA_FIELD.has_default_value = false
LOADACK_DATA_FIELD.default_value = nil
LOADACK_DATA_FIELD.message_type = LOADDATA
LOADACK_DATA_FIELD.type = 11
LOADACK_DATA_FIELD.cpp_type = 10

LOADACK.name = "LoadAck"
LOADACK.full_name = ".LoadAck"
LOADACK.nested_types = {}
LOADACK.enum_types = {}
LOADACK.fields = {LOADACK_GATEID_FIELD, LOADACK_INGATEID_FIELD, LOADACK_DATA_FIELD}
LOADACK.is_extendable = false
LOADACK.extensions = {}
CHECKANDNOTIFYOFFLINE_GATEID_FIELD.name = "gateId"
CHECKANDNOTIFYOFFLINE_GATEID_FIELD.full_name = ".CheckAndNotifyOffline.gateId"
CHECKANDNOTIFYOFFLINE_GATEID_FIELD.number = 1
CHECKANDNOTIFYOFFLINE_GATEID_FIELD.index = 0
CHECKANDNOTIFYOFFLINE_GATEID_FIELD.label = 2
CHECKANDNOTIFYOFFLINE_GATEID_FIELD.has_default_value = false
CHECKANDNOTIFYOFFLINE_GATEID_FIELD.default_value = 0
CHECKANDNOTIFYOFFLINE_GATEID_FIELD.type = 5
CHECKANDNOTIFYOFFLINE_GATEID_FIELD.cpp_type = 1

CHECKANDNOTIFYOFFLINE_INGATEID_FIELD.name = "inGateId"
CHECKANDNOTIFYOFFLINE_INGATEID_FIELD.full_name = ".CheckAndNotifyOffline.inGateId"
CHECKANDNOTIFYOFFLINE_INGATEID_FIELD.number = 2
CHECKANDNOTIFYOFFLINE_INGATEID_FIELD.index = 1
CHECKANDNOTIFYOFFLINE_INGATEID_FIELD.label = 2
CHECKANDNOTIFYOFFLINE_INGATEID_FIELD.has_default_value = false
CHECKANDNOTIFYOFFLINE_INGATEID_FIELD.default_value = 0
CHECKANDNOTIFYOFFLINE_INGATEID_FIELD.type = 5
CHECKANDNOTIFYOFFLINE_INGATEID_FIELD.cpp_type = 1

CHECKANDNOTIFYOFFLINE_GUID_FIELD.name = "guid"
CHECKANDNOTIFYOFFLINE_GUID_FIELD.full_name = ".CheckAndNotifyOffline.guid"
CHECKANDNOTIFYOFFLINE_GUID_FIELD.number = 3
CHECKANDNOTIFYOFFLINE_GUID_FIELD.index = 2
CHECKANDNOTIFYOFFLINE_GUID_FIELD.label = 2
CHECKANDNOTIFYOFFLINE_GUID_FIELD.has_default_value = false
CHECKANDNOTIFYOFFLINE_GUID_FIELD.default_value = ""
CHECKANDNOTIFYOFFLINE_GUID_FIELD.type = 9
CHECKANDNOTIFYOFFLINE_GUID_FIELD.cpp_type = 9

CHECKANDNOTIFYOFFLINE.name = "CheckAndNotifyOffline"
CHECKANDNOTIFYOFFLINE.full_name = ".CheckAndNotifyOffline"
CHECKANDNOTIFYOFFLINE.nested_types = {}
CHECKANDNOTIFYOFFLINE.enum_types = {}
CHECKANDNOTIFYOFFLINE.fields = {CHECKANDNOTIFYOFFLINE_GATEID_FIELD, CHECKANDNOTIFYOFFLINE_INGATEID_FIELD, CHECKANDNOTIFYOFFLINE_GUID_FIELD}
CHECKANDNOTIFYOFFLINE.is_extendable = false
CHECKANDNOTIFYOFFLINE.extensions = {}
KICKOFF_GUID_FIELD.name = "guid"
KICKOFF_GUID_FIELD.full_name = ".KickOff.guid"
KICKOFF_GUID_FIELD.number = 1
KICKOFF_GUID_FIELD.index = 0
KICKOFF_GUID_FIELD.label = 2
KICKOFF_GUID_FIELD.has_default_value = false
KICKOFF_GUID_FIELD.default_value = ""
KICKOFF_GUID_FIELD.type = 9
KICKOFF_GUID_FIELD.cpp_type = 9

KICKOFF.name = "KickOff"
KICKOFF.full_name = ".KickOff"
KICKOFF.nested_types = {}
KICKOFF.enum_types = {}
KICKOFF.fields = {KICKOFF_GUID_FIELD}
KICKOFF.is_extendable = false
KICKOFF.extensions = {}

CheckAndNotifyOffline = protobuf.Message(CHECKANDNOTIFYOFFLINE)
KickOff = protobuf.Message(KICKOFF)
LoadAck = protobuf.Message(LOADACK)
LoadData = protobuf.Message(LOADDATA)
LoadReq = protobuf.Message(LOADREQ)

